name: Deploy Resource Planning Cloud Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      function:
        description: 'Function to deploy (all, kapa1, kapa2)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - kapa1
          - kapa2

jobs:
  deploy-kapa-1:
    name: Deploy Kapa 1.0
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.event_name == 'push' || github.event.inputs.function == 'all' || github.event.inputs.function == 'kapa1' }}
    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/639051812907/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-cloud-function-deployer@circular-ether-368213.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v3'
      timeout-minutes: 10
      with:
        name: 'resource-planning-loader-kapa1'
        region: 'europe-west3'
        source_dir: './src/'
        runtime: 'python312'
        entry_point: 'main'
        memory: '2048M'
        environment_variables: 'CONFIG_GROUP=kapa_1_0'
        max_instance_count: 3
        max_instance_request_concurrency: 1
        ingress_settings: 'ALLOW_ALL'
        service_account: 'sheets-bigquery-sa@circular-ether-368213.iam.gserviceaccount.com'
        service_timeout: '540s'
        event_trigger_type: 'google.cloud.pubsub.topic.v1.messagePublished'
        event_trigger_pubsub_topic: 'projects/circular-ether-368213/topics/resource-planning-loader-kapa1'
        event_trigger_retry: true

  deploy-kapa-2:
    name: Deploy Kapa 2.0
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.event_name == 'push' || github.event.inputs.function == 'all' || github.event.inputs.function == 'kapa2' }}
    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/639051812907/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-cloud-function-deployer@circular-ether-368213.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v3'
      timeout-minutes: 10
      with:
        name: 'resource-planning-loader-kapa2'
        region: 'europe-west3'
        source_dir: './src/'
        runtime: 'python312'
        entry_point: 'main'
        memory: '2048M'
        environment_variables: 'CONFIG_GROUP=kapa_2_0'
        max_instance_count: 3
        max_instance_request_concurrency: 1
        ingress_settings: 'ALLOW_ALL'
        service_account: 'sheets-bigquery-sa@circular-ether-368213.iam.gserviceaccount.com'
        service_timeout: '540s'
        event_trigger_type: 'google.cloud.pubsub.topic.v1.messagePublished'
        event_trigger_pubsub_topic: 'projects/circular-ether-368213/topics/resource-planning-loader-kapa2'
        event_trigger_retry: true
